

// export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
// export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN'
// export const AUTH_USER = 'AUTH_USER'
// export const UNAUTH_USER = 'UNAUTH_USER'
// export const FETCHING_USER = 'FETCHING_USER'
// export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
// export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
// export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'

export const FETCHING_AUTH = 'FETCHING_AUTH'
export const FETCHING_CURRENT_USER_SUCCESS = 'FETCHING_CURRENT_USER_SUCCESS'
export const FETCHING_CURRENT_USER_FAILURE = 'FETCHING_CURRENT_USER_FAILURE'
export const SET_AUTH = 'SET_AUTH'
export const REMOVE_AUTH = 'REMOVE_AUTH'


// MOVS
export const FETCHING_MOVS = 'FETCH_ALL_MOVS'
export const FETCHING_MOVS_SUCCESS = 'FETCHING_MOVS_SUCCESS'
export const FETCHING_MOVS_FAILURE = 'FETCHING_MOVS_FAILURE'
export const SET_MOVS = 'SET_MOVS'
// export const ADD_MOV = 'ADD_MOV'
